# Generated by Django 3.1.6 on 2021-02-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='low_energy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='on_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='time_sensitive',
            field=models.BooleanField(default=False),
        ),
    ]
