# Generated by Django 3.1.6 on 2021-02-22 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_labels'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Labels',
            new_name='Label',
        ),
    ]
